# Generated by Django 5.2.6 on 2025-11-03 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Is Recurring'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='When the recurrence should stop (optional)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date'),
        ),
    ]
